name: Maker
favicon: null
layout_spectrum: 0.3843834358267486
typography_spectrum: 0.27955720061436296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5053792716935277
  lightness: 0.9177331384271383
  saturation: 0.7137373827863485
  rhythmicContrast: 0.8018250309396535
purpose: []
